### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Lovexd16** [Mrsluggan/GameDevs-5---backend#13]
En timer för hur länge man får rita/gissa

**Comment by patelsaurabh12** [comment]
> En timer för hur länge man får rita/gissa
import java.util.Timer;
import java.util.TimerTask;

public class TimerExample {
    
    private Timer timer;
    private int timeLimitInSeconds;

    public TimerExample(int timeLimitInSeconds) {
        this.timeLimitInSeconds = timeLimitInSeconds;
        timer = new Timer();
    }

    public void startTimer() {
        timer.schedule(new TimerTask() {
            int secondsPassed = 0;

            @Override
            public void run() {
                secondsPassed++;
                System.out.println("Tid: " + secondsPassed + " sekunder");

                if (secondsPassed >= timeLimitInSeconds) {
                    System.out.println("Tiden är slut!");
                    timer.cancel(); // Stoppat timern när tiden är slut
                }
            }
        }, 0, 1000); // Kör varje sekund
    }

    public static void main(String[] args) {
        TimerExample timerExample = new TimerExample(10); // 10 sekunder som exempel
        timerExample.startTimer();
    }
}

**Comment by Mrsluggan** [comment]
TACKAR
